version: '3.8'

services:
  postgres:
    image: postgres:16.0-bookworm
    container_name: fullstack-postgres
    environment:
      POSTGRES_USER: localadmin
      POSTGRES_PASSWORD: localpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: